/* 片區戶外生活節 2026 · 世界盃系列（益隆）— 市集攤主資料
   market.html（名單）同 brand.html（品牌頁）共用呢一份。
   欄位：c 攤位編號 | n 名 | t 分類標籤(filter 用) | cat 類別(顯示) | origin 來源
        | intro 介紹(留空=「整理緊」note) | ig handle | igUrl | site 官方網/頁 | photos[] 已 host 嘅相
   留空 intro 嘅 = 網上未搵到實證資料，待大會／商戶補；唔亂寫。 */
window.BRANDS=[
  {c:"A01", n:"Vamos", t:["retail"], cat:"服飾 · 生活選物", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A02", n:"Ace concept", t:["retail"], cat:"澳門原創運動服 · 球衣訂製", origin:"macau",
    intro:"Ace Concept Store 係澳門原創運動服品牌，做球隊隊衫、團體制服同客製化波衫印字，亦有引入日本職業足球會球衣同周邊。門市喺澳門荷蘭園大馬路。",
    ig:"@aceconceptstore", igUrl:"https://www.instagram.com/aceconceptstore/", site:"https://www.aceconceptstore.com/", photos:[]},
  {c:"A03", n:"U3G1 X EC VINTAGE", t:["retail"], cat:"古著 · vintage（聯乘）", origin:"",
    intro:"EC VINTAGE 係古著／二手衣物店，今次以與 U3G1 聯乘形式擺檔。",
    ig:"@ec_vintage_store", igUrl:"https://www.instagram.com/ec_vintage_store/", site:"", photos:[]},
  {c:"A04", n:"Avenue", t:["retail","hk"], cat:"潮流波鞋 · 服飾選物店", origin:"hong-kong",
    intro:"AVENUE 係主打潮流波鞋同服飾嘅多品牌選物店，喺香港多個商場設點，澳門亦有分店。",
    ig:"@avenue.hk", igUrl:"https://www.instagram.com/avenue.hk/", site:"", photos:[]},
  {c:"A05", n:"CHUMS", t:["retail"], cat:"日系戶外休閒品牌", origin:"japan",
    intro:"CHUMS 1983 年源自美國，後喺日本大熱，以紅腳鰹鳥（Booby Bird）做標誌，主打繽紛色調嘅服飾、背囊同配件。香港由官方帳號 @chums_hk 營運。",
    ig:"@chums_hk", igUrl:"https://www.instagram.com/chums_hk/", site:"", photos:[]},
  {c:"A06", n:"BOL OFFICIAL", t:["retail","bol"], cat:"城市戶外 × 機能街頭", origin:"macau",
    intro:"BOL 係澳門城市戶外品牌，著眼機能街頭（techwear）同戶外場景。由日常通勤到郊野使用，講求剪裁、面料同實際功能。A06 係 BOL 官方攤位，集合品牌主要系列。",
    ig:"@bol.official", igUrl:"https://www.instagram.com/bol.official/", site:"https://www.bolmacau.com/", photos:[]},
  {c:"A07", n:"HMAD.official", t:["retail","hk"], cat:"香港 denim remake · 改造服飾", origin:"hong-kong",
    intro:"HMAD 係香港改造服飾品牌，專做牛仔褲 remake 同 boro（日式補綴）拼接，招牌系列有 Lock In Jeans，亦做飾物同單品，走街頭風格。",
    ig:"@hmad.official_", igUrl:"https://www.instagram.com/hmad.official_/", site:"https://hmadofficial.com/", photos:[]},
  {c:"A08", n:"SWAG", t:["retail"], cat:"服飾 · 生活選物", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A09", n:"NEFC SOCCER SHOP x offfield", t:["retail","hk"], cat:"足球用品 · 球衣（聯乘）", origin:"hong-kong",
    intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A10", n:"拾衣 VINTAGE", t:["retail","hk"], cat:"香港古著 · 二手衣物", origin:"hong-kong",
    intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A11", n:"TE・MACAU & GOOFOPDESK", t:["retail"], cat:"澳門機能街頭 · 選物", origin:"macau",
    intro:"A11 由兩個澳門本地街頭品牌組成。TE.MACAU 係選物店，主理自家 label「turnover」並引入國際品牌；GOOFOPDESK（GOOF）係街頭服飾品牌，以波衫風格 graphic tee 同 jersey 為主，曾與 turnover 推出聯名。",
    ig:"@te.macau", igUrl:"https://www.instagram.com/te.macau/", site:"https://teclothing.co/", photos:[]},
  {c:"A12", n:"斗里 Doori", t:["fb"], cat:"餐飲 · 飲食", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A13", n:"HORIZON CAFE", t:["fb"], cat:"咖啡 · cafe", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A14", n:"百威啤酒 & VIDA", t:["fb"], cat:"啤酒 · 飲品", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A15", n:"趣眼釀酒廠", t:["fb"], cat:"澳門精釀啤酒", origin:"macau",
    intro:"趣眼釀酒廠（Funny Eye Brewery）係澳門首間本地精釀啤酒廠，2018 年由三位九十後創立，2020 年起做到 100% 澳門本地生產。以西式釀造結合東方茶同在地材料見稱，代表作係荔枝紅茶 Ale。",
    ig:"@funnyeyebrewery", igUrl:"https://www.instagram.com/funnyeyebrewery/", site:"https://funny-eye.com/", photos:[]},
  {c:"A16", n:"千林 CHINLAM WHISKY", t:["fb"], cat:"威士忌專店 · 獨立桶", origin:"macau",
    intro:"千林 CHIN LAM 係澳門威士忌專店，為客人搜羅稀有及高年份威士忌，亦會推出自家選桶（single cask）出品。店址南灣。",
    ig:"", igUrl:"", site:"https://www.facebook.com/chinlamwhiskey/", photos:[]},
  {c:"A17", n:"Kitda 驚喜蛋 / 賞食", t:["fb"], cat:"零食 · 食玩", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A18", n:"璧茶", t:["fb"], cat:"茶飲", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A19", n:"Blooom coffee & NATA", t:["fb"], cat:"手沖咖啡 · 烘焙（+ 葡撻）", origin:"macau",
    intro:"Blooom Coffee 係澳門咖啡品牌，2012 年創立，被視為澳門首間獨立咖啡烘焙店，主打本地新鮮烘焙咖啡豆，設多間分店。今次以咖啡配葡式蛋撻（NATA）形式呈現。",
    ig:"@blooomcoffee", igUrl:"https://www.instagram.com/blooomcoffee/", site:"https://blooomcoffeehouse.com/", photos:[]},
  {c:"A20", n:"茶水 Teawater", t:["fb"], cat:"台式手搖茶飲", origin:"macau",
    intro:"茶水 Tea Water 係源自台灣嘅手搖茶飲品牌，已落地澳門開分店。主打天然茶湯同時令鮮果即製，招牌有現榨鮮果茶、奶蓋茶。",
    ig:"@teawater_macau", igUrl:"https://www.instagram.com/teawater_macau/", site:"", photos:[]},
  {c:"A21", n:"YouCHICO", t:["retail"], cat:"服飾 · 生活選物", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A22", n:"Macau Impressions", t:["retail"], cat:"澳門設計 · 紀念品", origin:"macau", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A23", n:"M PASS", t:["retail"], cat:"服飾 · 生活選物", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A24", n:"Die.\\/.young", t:["retail","hk"], cat:"香港街頭服飾", origin:"hong-kong", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A25", n:"FUGGLER", t:["retail"], cat:"毛公仔 · 收藏玩具", origin:"uk",
    intro:"FUGGLER 係源自英國嘅「醜得可愛」毛公仔品牌，香港設有官方旗艦店（銅鑼灣 Hysan Place）。產品包括毛公仔、盲盒同生活雜貨。",
    ig:"@fugglerofficial.hk", igUrl:"https://www.instagram.com/fugglerofficial.hk/", site:"https://www.fuggler.com/", photos:[]},
  {c:"A26", n:"WHAT ELEPHANT", t:["retail"], cat:"服飾 · 生活選物", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A27", n:"Toby Black", t:["retail","hk"], cat:"香港 服飾 · 生活", origin:"hong-kong", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A28", n:"Microwave Studio", t:["retail","hk"], cat:"香港 插畫 · 創作工作室", origin:"hong-kong",
    intro:"Microwave Studio 係香港插畫／動畫創作工作室，作品涵蓋插畫、動畫同聲音設計。",
    ig:"@microwavestudio", igUrl:"https://www.instagram.com/microwavestudio/", site:"https://microwavestudio.myportfolio.com/", photos:[]},
  {c:"A29", n:"面部彩繪", t:["exp"], cat:"活動體驗 · 面部彩繪", origin:"",
    intro:"現場面部彩繪攤位，由專人即場為大細朋友畫上世界盃應援彩繪同圖案。",
    ig:"", igUrl:"", site:"", photos:[]},
  {c:"A30", n:"世界杯應援 DIY", t:["exp"], cat:"活動體驗 · 應援 DIY", origin:"",
    intro:"世界盃應援 DIY 攤位，現場整應援小物（如打氣牌、隊旗、配飾），即整即拎走。",
    ig:"", igUrl:"", site:"", photos:[]},
  {c:"A31", n:"Snapio 自拍亭", t:["exp"], cat:"自助自拍亭 · photobooth", origin:"hong-kong",
    intro:"Snapio 係 2019 年成立嘅香港自拍亭品牌，喺香港、澳門、台灣設有多個據點，提供即影即有四格相自拍亭，亦承接活動租用。",
    ig:"@snapio.io", igUrl:"https://www.instagram.com/snapio.io/", site:"https://www.snapio.io/", photos:[]},
  {c:"A32", n:"KIVA MACAU", t:["fb"], cat:"餐飲 · 飲食", origin:"macau", intro:"",
    ig:"@kivamacau", igUrl:"https://www.instagram.com/kivamacau/", site:"", photos:[]},
  {c:"A33", n:"DIGREEN", t:["fb"], cat:"澳門雪糕 · 茶飲", origin:"macau",
    intro:"DIGREEN 係源自澳門嘅雪糕同茶飲品牌，主打自家研發嘅原創軟雪糕，標榜唔加香精，喺官也街、新八佰伴、永利等地設點。",
    ig:"@digreen.macau", igUrl:"https://www.instagram.com/digreen.macau/", site:"https://digreengroup.com/", photos:[]},
  {c:"A34", n:"泰谷", t:["fb"], cat:"澳門泰國菜", origin:"macau",
    intro:"泰谷（Let's Thai）係位於澳門黑沙環嘅泰國菜餐廳，供應咖喱、冬蔭功等泰式菜式。",
    ig:"@lets.thai", igUrl:"https://www.instagram.com/lets.thai/", site:"", photos:[]},
  {c:"A35", n:"萬草堂", t:["fb"], cat:"餐飲 · 飲品", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A36", n:"Baobao bakery", t:["fb"], cat:"麵包 · 烘焙", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A37", n:"聖杯", t:["fb"], cat:"餐飲 · 飲品", origin:"", intro:"", ig:"", igUrl:"", site:"", photos:[]},
  {c:"A38", n:"BOL POPUP", t:["retail","bol"], cat:"BOL 期間限定", origin:"macau",
    intro:"BOL POPUP 係 BOL 喺市集嘅期間限定攤位，帶嚟揀選嘅機能街頭同戶外單品，部分為市集限定。BOL 定位城市戶外 × 機能街頭，講求功能同場景。",
    ig:"@bol.official", igUrl:"https://www.instagram.com/bol.official/", site:"https://www.bolmacau.com/", photos:[]},
  {c:"A39", n:"SUPER GROUP", t:["retail"], cat:"服飾 · 生活選物", origin:"macau", intro:"",
    ig:"@supergroup.macau", igUrl:"https://www.instagram.com/supergroup.macau/", site:"", photos:[]}
];
